spring:
  application:
    name: UserService

    profiles:
      active: ${ENV:local}

  # PostgreSQL datasource configuration
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}


  # JPA / Hibernate configuration
  jpa:
    hibernate:
      ddl-auto: update

    show-sql: true

# Application server configuration
server:
  port: 8082
  
management:
  health:
    circuitbreakers:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-components: always
      show-details: always
resilience4j:
  circuitbreaker:
    instances:
      getResturantOwnerBreaker:
        register-health-indicator: true
        event-consumer-buffer-size: 10
        failure-rate-threshold: 50
        minimum-number-of-calls: 5
        automatic-transition-from-open-to-half-open-enabled: true
        wait-duration-in-open-state:
          seconds: 45
        permitted-number-of-calls-in-half-open-state: 3
        sliding-window-size: 10
        sliding-window-type: COUNT_BASED