spring:
  application:
    name: UserService

    profiles:
      active: ${ENV:local}

  # PostgreSQL datasource configuration
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}


  # JPA / Hibernate configuration
  jpa:
    hibernate:
      ddl-auto: update

    show-sql: true

# Application server configuration
server:
  port: 8082