spring:
  application:
    name: ApiGatewayService

  cloud:
    gateway:
      server:
        webflux:
          discovery:
            locator:
              enabled: true
              lower-case-service-id: true
#      server:
#        webmvc:
#          routes:
#            - id: RESTAURANTSERVICE
#              uri: lb://RESTAURANTSERVICE
#              predicates:
#                - Path=/restaurants-service/**
#              filters:
#                - StripPrefix=1
#
#            - id: USERSERVICE
#              uri: lb://USERSERVICE
#              predicates:
#                - Path=/users-service/**
#              filters:
#                - StripPrefix=1

eureka:
  client:
    # Tells this service to register itself with the Eureka server
    register-with-eureka: true
    # Tells this service to fetch the registry of other services from Eureka
    fetch-registry: true
    # The URL of the Eureka Server to connect to
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    # Prefer to use the service's IP address for registration instead of its hostname.
    # This is often more reliable in containerized environments like Docker.
    prefer-ip-address: true

logging:
  level:
    org.springframework.cloud.gateway: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: gateway